simulation: True
visualization: false
branching_sqrt: 2
FOV: 1.57
min_footprint: 5.0
speed: 1
area_length: 128.0
area_rotation: 0.0
logging: false
auto_exit: true
bypass_controller: true
int_prob_thr: 0.3
prob_r: 0.9
